version: "2"
services:
     wwwserver:
          build: .
          image: dieaquino/phpwebapp
          environment:
               PORT: 80
          ports:
               - "80:80"
          volumes:
               - ./html:/var/www/html
          
