apiVersion: apps/v1
kind: Deployment
metadata:
  name: waf 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: waf 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: waf 
    spec:
      containers:
      - name: modsecurity-proxy
        image: fareoffice/modsecurity
        imagePullPolicy: Always
        env:
          # Webservice
        - name: PROXY_UPSTREAM_HOST
          value: "testapp:80"
        - name: PARANOIA
          value: "1"
        - name: SEC_RULE_ENGINE
          value: "DetectionOnly"  #On/Off/DetectionInly
        ports:
          - containerPort: 80
          # Limit resources for GKE g1-small instance
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 20m
#       livenessProbe:
#         tcpSocket:
#           port: 80
#         initialDelaySeconds: 10
#         timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: waf 
spec:
  selector:
    name: waf 
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
